import type { PipeTransform } from "@angular/core";
import { Pipe } from "@angular/core";

const ROLES_TO_TRANSLATE: Record<string, string> = {
  "Chief Financial Officer": "Directeur financier",
  "Chief Executive Officer": "Directeur général",
  "Chief Operating Officer": "Directeur des opérations",
  "Marketing Manager": "Responsable marketing",
  "Deputy Manager": "Directeur adjoint",
  "Property Manager": "Gestionnaire immobilier",
  "Operations Manager": "Responsable des opérations",
  "Managing Director": "Directeur général",
  "Real Estate Agent": "Agent immobilier",
  "Real Estate Advisor": "Conseiller immobilier",
  "Sales Manager": "Responsable des ventes",
  "HR Manager": "Responsable des ressources humaines",
  "IT Manager": "Responsable informatique",
  "Software Engineer": "Ingénieur logiciel",
  "Data Migration Director": "Directeur de la migration des données",
  "Real Estate Consultant": "Consultant immobilier",
  President: "Président",
  "Development Manager": "Responsable du développement",
  "Contact officer": "Responsable des contacts",
  "Agency Director": "Directeur d'agence",
  "Property Management Assistant": "Assistant gestion immobilière",
  "Account Manager": "Gestionnaire de comptes",
  "Property Accountant": "Comptable immobilier",
  "Branch Manager": "Responsable d'agence",
  "Regional Service Manager": "Responsable régional des services",
  "Technical Advisor, Social Work and Professional Development":
    "Conseiller technique, travail social et développement professionnel",
  "Administrative Assistant": "Assistant administratif",
  "General Secretary": "Secrétaire général",
  "Deputy Director": "Directeur adjoint",
  "Head of Communications": "Responsable de la communication",
  Accountant: "Comptable",
  "Accounting Assistant": "Assistant comptable",
  "Accounting Manager": "Responsable comptable",
  "Agency Manager": "Responsable d'agence",
  "Asset Manager": "Gestionnaire d'actifs",
  Assistant: "Assistant",
  "Career Advisor": "Conseiller carrière",
  CEO: "Directeur général",
  CFO: "Directeur financier",
  "Chief of Staff": "Chef de cabinet",
  "Commercial Manager": "Responsable commercial",
  Director: "Directeur",
  "Executive Assistant": "Assistant de direction",
  "Finance Manager": "Responsable financier",
  "General Director": "Directeur général",
  "HR Partner": "Partenaire RH",
  "Human Resources Manager": "Responsable des ressources humaines",
  Intern: "Stagiaire",
  "Junior Property Manager": "Gestionnaire immobilier junior",
  "Land Project Manager": "Chef de projet foncier",
  "Legal Counsel": "Conseiller juridique",
  "Legal Director": "Directeur juridique",
  Manager: "Responsable",
  "Managing Partner": "Associé gérant",
  Negotiator: "Négociateur",
  "Operations Director": "Directeur des opérations",
  "Partnership Manager": "Responsable partenariats",
  "Payroll Manager": "Responsable paie",
  "Product Owner": "Responsable produit",
  "Project Manager": "Chef de projet",
  Receptionist: "Réceptionniste",
  "Real Estate Manager": "Responsable immobilier",
  "Real Estate Negotiator": "Négociateur immobilier",
  "Rental Consultant": "Conseiller location",
  "Regional Manager": "Responsable régional",
  "Sales Assistant": "Assistant commercial",
  "Sales Consultant": "Consultant commercial",
  "Sales Director": "Directeur commercial",
  "SEO Specialist": "Spécialiste SEO",
  "Site Manager": "Responsable de site",
  "Technical Manager": "Responsable technique",
  "Transaction Manager": "Responsable des transactions",
  "Vice President": "Vice-président",
};
@Pipe({
  name: "ExternalContactRole",
})
export class ExternalContactRolePipe implements PipeTransform {
  transform(role: string | null | undefined) {
    return role ? (ROLES_TO_TRANSLATE[role] ?? role) : "Non connu";
  }
}
