CREATE TABLE IF NOT EXISTS "simulated_locations" (
	"id_pg" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"street_number" text,
	"street_name" text,
	"street_view_url" text,
	"zipcode" text,
	"city" text,
	"raw_bdnb" jsonb,
	"sector" "secteur_enum",
	"building_count" real,
	"units_count" real,
	"m2" real,
	"storeys_count" real,
	"glazing_surface_percentage" real,
	"height" real,
	"energy_type" "type_d_energie_enum",
	"heating_system" "type_de_chauffage_enum",
	"electricity_consumption_per_m2" real,
	"greenhouse_gas_emissions_per_m2" real,
	"geom_group" jsonb,
	"creation_date" date,
	"heating_type" text,
	"dpe_label" text,
	"account_name" text,
	"building_name" text,
	"most_profitable_operation" text
);
