DO $$ BEGIN
 CREATE TYPE "public"."prestation_enum" AS ENUM(
   'DPE COLLECTIF + PPT',
   'AUDIT ENERGÉTIQUE',
   'DTG + PPT',
   'OPERAT',
   'ISOLATION DES COMBLES',
   'ITE',
   'ISOLATION PLANCHER',
   'FENETRES',
   'ISOLATION TOITURES TERRASSES',
   'REVET RÉFLECTIF',
   'CHAUDIERE HPE',
   'POMPE A CHALEUR',
   'VENTILATION DOUBLE FLUX',
   'VENTILATION SIMPLE FLUX',
   'VENTILO CONVECTEUR',
   'DESTRATIFICATION DE L''AIR',
   'PAC AIR-AIR',
   'PAC AIR-AIR NON RÉVERSIBLE',
   'CALORIFUGEAGE',
   'BALLON THERMODYNAMIQUE',
   'POINTS SINGULIERS',
   'EQUILIBRAGE',
   'ROBINET THERMOSTATIQUE',
   'CHAUDIÈRE BIOMASSE',
   'OPTIMISEUR DE RELANCE EN CHAUFFAGE COLLECTIF',
   'VENTILATION HYBRIDE HYGRORÉGLABLE',
   'DÉSEMBOUAGE',
   'GTB',
   'LED',
   'LUMIÈRE EXTÉRIEURE',
   'PANNEAUX SOLAIRES',
   'CHAUFFE-EAU SOLAIRE',
   'RECUP CHALEUR EAUX GRISES',
   'SYSTÈMES HYDRO-ECONOMES',
   'GROUPE FROID',
   'RECUP CHALEUR TOUR AERO',
   'RÉNOVATION GLOBALE',
   'CONTRAT ELECTRICITE',
   'CONTRAT GAZ'
 );
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "deals" ALTER COLUMN "prestations" SET DATA TYPE prestation_enum USING prestations::prestation_enum;
