ALTER TABLE "batiments" ADD COLUMN "hauteur_mean" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "classe_inertie" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "presence_balcon" boolean;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nb_log" integer;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nb_log_rnc" integer;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nb_lot_tertiaire_rnc" integer;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nb_pdl_res_dle_elec_2020" integer;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nb_pdl_pro_dle_elec_2020" integer;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nb_pdl_pro_dle_gaz_2020" integer;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nb_pdl_res_dle_gaz_2020" integer;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "classe_bilan_dpe" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "arrete_2021" boolean;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "identifiant_dpe" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "emission_ges_5_usages_m2" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "emission_ges_3_usages_ep_m2_arrete_2012" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_ventilation" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_generateur_climatisation" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_generateur_climatisation_anciennete" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_isolation_mur_exterieur" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "u_mur_exterieur" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_isolation_plancher_bas" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_isolation_plancher_haut" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "u_plancher_bas_final_deperditif" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "u_plancher_haut_deperditif" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_vitrage" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_materiaux_menuiserie" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_gaz_lame" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "type_fermeture" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "vitrage_vir" boolean;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "u_baie_vitree" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "facteur_solaire_baie_vitree" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "conso_pro_dle_elec_2020" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "conso_res_dle_elec_2020" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "conso_pro_dle_gaz_2020" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "conso_res_dle_gaz_2020" real;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "id_reseau" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "alea_radon" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "alea_argiles" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "quartier_prioritaire" boolean;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "nom_quartier_qpv" text;--> statement-breakpoint
ALTER TABLE "batiments" ADD COLUMN "code_qp" text;