ALTER TABLE "batiments_bdnb_stats" ADD COLUMN "nb_siren_only" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "batiments_bdnb_stats" ADD COLUMN "nb_siret" integer DEFAULT 0 NOT NULL;

-- Backfill for nb_siren_only and nb_siret (dedup + update only if values differ)
-- WITH counts AS (
--   SELECT
--     assoc.batiments_bdnb_id_pg AS location_uuid,
--     count(distinct case
--       when pm.siret is not null and pm.siret <> '' then assoc.personne_morale_id_pg
--       else null
--     end) AS nb_siret,
--     count(distinct case
--       when (pm.siren is not null and pm.siren <> '')
--        and (pm.siret is null or pm.siret = '') then assoc.personne_morale_id_pg
--       else null
--     end) AS nb_siren_only
--   FROM associations_batiments_bdnb_personne_morale assoc
--   LEFT JOIN personne_morale pm
--     ON pm.id_pg = assoc.personne_morale_id_pg
--   GROUP BY assoc.batiments_bdnb_id_pg
-- )
-- INSERT INTO batiments_bdnb_stats (
--   batiments_bdnb_id_pg,
--   nb_siret,
--   nb_siren_only
-- )
-- SELECT
--   b.id_pg,
--   COALESCE(c.nb_siret, 0),
--   COALESCE(c.nb_siren_only, 0)
-- FROM batiments_bdnb b
-- LEFT JOIN counts c
--   ON c.location_uuid = b.id_pg
-- LEFT JOIN batiments_bdnb_stats s
--   ON s.batiments_bdnb_id_pg = b.id_pg
-- WHERE COALESCE(s.nb_siret, 0) IS DISTINCT FROM COALESCE(c.nb_siret, 0)
--    OR COALESCE(s.nb_siren_only, 0) IS DISTINCT FROM COALESCE(c.nb_siren_only, 0)
-- ON CONFLICT (batiments_bdnb_id_pg) DO UPDATE
-- SET
--   nb_siret = EXCLUDED.nb_siret,
--   nb_siren_only = EXCLUDED.nb_siren_only;
