import { defineConfig } from "tsup";

// Variables d'environnement à injecter
const environment = {
  DATABASE_URL: process.env.DATABASE_URL,
  GOOGLE_CLOUD_PROJECT: process.env.GOOGLE_CLOUD_PROJECT || "local",
  SUPABASE_ADMIN_KEY: process.env.SUPABASE_ADMIN_KEY,
  STACKSYNC_BEARER_TOKEN: process.env.STACKSYNC_BEARER_TOKEN,
  YOUSIGN_API_KEY: process.env.YOUSIGN_API_KEY,
  YOUSIGN_WEBHOOK_SECRET_KEY: process.env.YOUSIGN_WEBHOOK_SECRET_KEY,
  OPENAI_ASSISTANT_API_KEY: process.env.OPENAI_ASSISTANT_API_KEY,
  MAILERSEND_API_KEY: process.env.MAILERSEND_API_KEY,
  SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
  SENTRY_API_DSN: process.env.SENTRY_API_DSN,
  PDFSHIFT_API_KEY: process.env.PDFSHIFT_API_KEY,
  PAPPERS_API_KEY: process.env.PAPPERS_API_KEY,
  HUNTER_API_KEY: process.env.HUNTER_API_KEY,
  FULLENRICH_API_KEY: process.env.FULLENRICH_API_KEY,
  SOCIETE_INFO_API_KEY: process.env.SOCIETE_INFO_API_KEY,
  VITE_ENV: process.env.VITE_ENV,
  VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL,
  VITE_SENTRY_RELEASE: process.env.VITE_SENTRY_RELEASE,
  SHOWCASE_LINK: process.env.SHOWCASE_LINK,
  CEELAB_LINK: process.env.CEELAB_LINK,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  VITE_STRIPE_PUBLIC_KEY: process.env.VITE_STRIPE_PUBLIC_KEY,
  STRIPE_PRICE_ESSENTIAL: process.env.STRIPE_PRICE_ESSENTIAL,
  STRIPE_PRICE_PRO: process.env.STRIPE_PRICE_PRO,
  STRIPE_PRICE_BUSINESS: process.env.STRIPE_PRICE_BUSINESS,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
  MICROSOFT_CLIENT_ID: process.env.MICROSOFT_CLIENT_ID,
  MICROSOFT_CLIENT_SECRET: process.env.MICROSOFT_CLIENT_SECRET,
  MICROSOFT_REDIRECT_URI: process.env.MICROSOFT_REDIRECT_URI,
  OAUTH_TOKEN_ENCRYPTION_KEY: process.env.OAUTH_TOKEN_ENCRYPTION_KEY,
};

export default defineConfig({
  entry: ["apps/api/src/firebase-entry.ts"],
  outDir: "dist/apps/api",
  format: ["esm"],
  target: "node20",
  sourcemap: true,
  dts: false,
  splitting: false,
  clean: true,
  define: {
    "process.env": JSON.stringify(environment),
  },
});
